version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.31
    tmpfs: /var/lib/mysql
    ports:
      - 3306:3306
    volumes:
      - data:/var/cache
      - ".docker/mysql.init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  data:
    driver: local
